test3

diff --git a/.github/workflows/buildPR.yml b/.github/workflows/buildPR.yml
--- a/.github/workflows/buildPR.yml
+++ b/.github/workflows/buildPR.yml
@@ -67,7 +67,7 @@ jobs:
             - name: Build Project
               run: ./gradlew assemble
 
-
+#firs action
             - uses: appleboy/telegram-action@master
               with:
                   to: ${{ secrets.TELEGRAM_MOHSEN_ID }}
@@ -76,6 +76,7 @@ jobs:
                   message: 'Hi sir build branch *[${{ github.head_ref }}]* get started! 🚀'
                   document: ${{ github.workspace }}/app/build/outputs/apk/debug/**.apk
 
+#secound action
             - name: Share Apk on Telegram
               if: ${{ success() }}
               env:
@@ -83,15 +84,18 @@ jobs:
                   TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
                   TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_CHANNEL_TOPIC_ID }}
                   MESSAGE: 'Debug APK Build for branch *[${{ github.head_ref }}]* in Progress! 🏗️📱⬇️🚀📎 Keep an Eye'
-                  APK_PATH: ${{ github.workspace }}/app/build/outputs/apk/debug/**.apk
               run: |
-                  curl -4 -s -S -L -w"\n" -o- \
-                    -F document=@"${APK_PATH}" \
-                    -F parse_mode='Markdown' \
-                    -F caption="${MESSAGE}" \
-                    -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument \
-                    -F chat_id="${TELEGRAM_CHANNEL_ID}" \
-                    -F message_thread_id=${TELEGRAM_TOPIC_ID}
+                APK_PATH=$(find ${{ github.workspace }}/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
+                if [ -f "$APK_PATH" ]; then
+                curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
+                -F chat_id="${TELEGRAM_CHANNEL_ID}" \
+                -F message_thread_id="${TELEGRAM_TOPIC_ID}" \
+                -F document=@"${APK_PATH}" \
+                -F caption="${MESSAGE}"
+                else
+                echo "APK file not found."
+                exit 1
+                fi
 
             - name: Share app build failure on Telegram
               if: ${{ failure() }}
